/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/zones/{zone_id}/categories/{categorie_slug}/forcage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Force l'état d'une catégorie dans une ville (ZON-02). Journalisé via outbox
         *     (categorie.forcage_change + categorie.activation_changee si bascule) dans la
         *     même transaction.
         */
        put: operations["forcer_categorie"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/deconnexion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Révoque la session courante (déconnexion locale). */
        post: operations["deconnexion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/inscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crée le compte après consentement ARTCI, puis ouvre sa session. */
        post: operations["inscrire"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/demander": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demande l'envoi d'un code OTP. Réponse TOUJOURS neutre (SC-003). */
        post: operations["demander"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verifier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vérifie le code : ouvre une session (numéro connu) ou exige le consentement. */
        post: operations["verifier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/rafraichir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Échange le refresh contre un nouvel accès (rotation systématique, R2). */
        post: operations["rafraichir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Configuration produit publique d'une zone (ZON-04). PUBLIC en lecture seule
         *     (clarification Q1), liste blanche de namespaces (R4), versionnée par ETag
         *     (304 sur If-None-Match — polling horaire économe).
         */
        get: operations["config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sonde de vie du service. Répond `200 {status:"ok", version}`. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compte courant et états de TOUS ses rôles. */
        get: operations["moi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moi/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Appareils/sessions actifs du compte (FR-008). */
        get: operations["mes_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moi/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Déconnexion à distance d'un appareil (SC-004). */
        delete: operations["revoquer_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Réponse UNIQUE de `/auth/otp/demander`. */
        Accepte: {
            /**
             * @description Toujours `comptes.otp.envoye_si_valide`.
             * @example comptes.otp.envoye_si_valide
             */
            message_cle: string;
        };
        /** @description Appareil déclaré par l'app à l'ouverture de session. */
        AppareilDto: {
            /** @description Nom lisible (« Pixel 7 de poche »), affiché tel quel dans la liste. */
            nom: string;
            /** @description Plateforme. */
            plateforme: components["schemas"]["PlateformeDto"];
        };
        /** @description Catégorie active (contrat). */
        CategorieDto: {
            /** @description Mixable au panier (CMD-01). */
            mixable: boolean;
            /** @description Clé i18n fr du nom. */
            nom_cle: string;
            /** @description Slug de la catégorie. */
            slug: string;
        };
        /** @description Compte courant et l'état de TOUS ses rôles (contrat `CompteMoi`). */
        CompteMoi: {
            /**
             * Format: date-time
             * @description Création du compte.
             */
            cree_le: string;
            /**
             * Format: uuid
             * @description Identifiant du compte.
             */
            id: string;
            /** @description Rôles et leurs statuts (tous, pas seulement les valides). */
            roles: components["schemas"]["EtatRoleDto"][];
            /** @description Identité Mefali — aucune donnée nominative au MVP. */
            telephone_e164: string;
            /**
             * Format: uuid
             * @description Zone de rattachement.
             */
            zone_id: string;
        };
        /** @description Document `/config` (contrat) — sous-ensemble public de la config effective. */
        ConfigZone: {
            /** @description Catégories actives dans la zone. */
            categories: components["schemas"]["CategorieDto"][];
            /** @description Devise résolue. */
            devise: components["schemas"]["DeviseDto"];
            /** @description Drapeaux (clés `drapeau.*` sans préfixe). */
            drapeaux: {
                [key: string]: boolean;
            };
            /** @description Paramètres client (clés `client.*` sans préfixe). */
            parametres: Record<string, never>;
            /** @description Textes (clés `texte.*` sans préfixe) — clés i18n fr. */
            textes: {
                [key: string]: string;
            };
            /** @description Slugs des types de transport actifs. */
            transports_actifs: string[];
            /** @description Empreinte SHA-256 hex du document canonique (= ETag). */
            version: string;
            /**
             * Format: uuid
             * @description Zone servie.
             */
            zone: string;
        };
        /** @description Corps de la requête de forçage. */
        CorpsForcage: {
            /** @description Nouveau mode de forçage à appliquer. */
            forcage: components["schemas"]["ForcageDto"];
        };
        /** @description Corps de `POST /auth/otp/demander`. */
        DemandeOtp: {
            /** @description Saisie locale ou E.164 — normalisée avec l'indicatif de la zone (R4). */
            telephone: string;
            /**
             * Format: uuid
             * @description Zone de l'app (bootstrap Tiassalé — R13).
             */
            zone: string;
        };
        /** @description Corps de `POST /auth/rafraichir`. */
        DemandeRafraichissement: {
            /** @description Jeton de renouvellement opaque courant. */
            rafraichissement: string;
        };
        /** @description Devise (contrat) — montants entiers en unités mineures (principe III). */
        DeviseDto: {
            /** @description Code ISO 4217 (ex. XOF). */
            code: string;
            /**
             * Format: int32
             * @description Nombre de décimales des unités mineures (0 pour XOF).
             */
            decimales: number;
        };
        /** @description Corps d'erreur du contrat — `{ code, message_cle }`. */
        ErreurApi: {
            /** @description Code stable, exploitable par le client. */
            code: string;
            /** @description Clé i18n fr — aucune chaîne UI en dur (constitution VII). */
            message_cle: string;
        };
        /** @description État effectif d'une catégorie renvoyé après forçage (contrat). */
        EtatCategorie: {
            /** @description État EFFECTIF après application. */
            actif: boolean;
            /** @description Slug de la catégorie. */
            categorie: string;
            /** @description Mode de forçage appliqué. */
            forcage: components["schemas"]["ForcageDto"];
            /**
             * Format: uuid
             * @description Ville concernée.
             */
            zone: string;
        };
        /** @description État d'un rôle (contrat). */
        EtatRoleDto: {
            /**
             * Format: date-time
             * @description Horodatage de la dernière décision.
             */
            decide_le?: string | null;
            /** @description Motif de la dernière décision admin. */
            motif?: string | null;
            /** @description Rôle concerné. */
            role: string;
            /** @description Statut courant. */
            statut: string;
        };
        /**
         * @description Mode de forçage (contrat) — mappé sur [`zones::Forcage`].
         * @enum {string}
         */
        ForcageDto: "automatique" | "force_actif" | "force_inactif";
        /**
         * @description Réponse de la sonde de vie. Ne contient AUCUNE donnée sensible : la sonde
         *     mesure la disponibilité du processus (non authentifiée, constitution VIII).
         */
        HealthResponse: {
            /**
             * @description Toujours `"ok"` quand le processus répond.
             * @example ok
             */
            status: string;
            /** @description Version du binaire (`CARGO_PKG_VERSION`). */
            version: string;
        };
        /** @description Corps de `POST /auth/inscription`. */
        Inscription: {
            /** @description Version du texte ARTCI accepté — servie par la config de zone. */
            consentement_version: string;
            /** @description Émis par `/auth/otp/verifier`, usage unique, TTL 10 min. */
            jeton_inscription: string;
        };
        /** @description Paire de jetons (contrat). */
        JetonsDto: {
            /** @description JWT HS256, 15 min (claims sub/sid). */
            acces: string;
            /** @description Opaque 256 bits — tourne à chaque usage. */
            rafraichissement: string;
        };
        /**
         * @description Plateforme de l'appareil (contrat).
         * @enum {string}
         */
        PlateformeDto: "android" | "ios";
        /** @description Issue de `/auth/otp/verifier` — `oneOf` discriminé par `resultat`. */
        ResultatVerification: {
            /** @description Compte connecté. */
            compte: components["schemas"]["CompteMoi"];
            /** @description Jetons de l'appareil. */
            jetons: components["schemas"]["JetonsDto"];
            /** @enum {string} */
            resultat: "session";
        } | {
            /** @description Jeton d'inscription à usage unique. */
            jeton_inscription: string;
            /** @enum {string} */
            resultat: "consentement_requis";
        };
        /** @description Session/appareil du compte (contrat `SessionAppareil`). */
        SessionAppareil: {
            /** @description Nom déclaré par l'app. */
            appareil_nom: string;
            /** @description Plateforme. */
            appareil_plateforme: components["schemas"]["PlateformeDto"];
            /** @description Session de l'appareil appelant — celle qu'on ne se coupe pas par erreur. */
            courante: boolean;
            /**
             * Format: date-time
             * @description Ouverture.
             */
            cree_le: string;
            /**
             * Format: date-time
             * @description Dernier rafraîchissement.
             */
            derniere_activite_le: string;
            /**
             * Format: uuid
             * @description Identifiant de session.
             */
            id: string;
        };
        /** @description Corps de `POST /auth/otp/verifier`. */
        VerificationOtp: {
            /** @description Appareil — capté ici, conservé jusqu'à l'inscription (R3). */
            appareil: components["schemas"]["AppareilDto"];
            /** @description Code à 6 chiffres. */
            code: string;
            /** @description Le MÊME numéro que celui de la demande. */
            telephone: string;
            /**
             * Format: uuid
             * @description Zone de l'app.
             */
            zone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    forcer_categorie: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ville dont on force la catégorie. */
                zone_id: string;
                /** @description Slug de la catégorie. */
                categorie_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorpsForcage"];
            };
        };
        responses: {
            /** @description Nouveau mode appliqué ; état effectif. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtatCategorie"];
                };
            };
            /** @description Session absente, invalide ou révoquée. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle admin requis. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Zone ou catégorie inconnue. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Corps invalide (forcage hors énumération). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deconnexion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session révoquée. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session absente, invalide ou révoquée. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErreurApi"];
                };
            };
        };
    };
    inscrire: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Inscription"];
            };
        };
        responses: {
            /** @description Compte créé (réduit au numéro vérifié) + session ouverte. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatVerification"];
                };
            };
            /** @description Jeton d'inscription invalide, expiré (10 min) ou déjà consommé. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErreurApi"];
                };
            };
            /** @description Consentement absent — aucun compte n'est créé (FR-006). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErreurApi"];
                };
            };
        };
    };
    demander: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeOtp"];
            };
        };
        responses: {
            /** @description Réponse UNIQUE : numéro connu ou non, plafond atteint ou non. Chaque demande invalide le code précédent du numéro. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepte"];
                };
            };
            /** @description Numéro non normalisable — erreur de FORMAT, neutre quant à l'existence d'un compte. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErreurApi"];
                };
            };
        };
    };
    verifier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationOtp"];
            };
        };
        responses: {
            /** @description Vérification réussie — deux issues discriminées par `resultat`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatVerification"];
                };
            };
            /** @description Code faux, expiré (> 5 min) ou essais épuisés (3) — message NEUTRE unique, identique dans TOUS les cas d'échec. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErreurApi"];
                };
            };
            /** @description Numéro non normalisable. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErreurApi"];
                };
            };
        };
    };
    rafraichir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeRafraichissement"];
            };
        };
        responses: {
            /** @description Nouveaux jetons — l'ancien refresh est invalidé. Aucune expiration d'inactivité. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JetonsDto"];
                };
            };
            /** @description Refresh inconnu, session révoquée, OU réutilisation d'un jeton déjà tourné —                                       dans ce dernier cas la session est RÉVOQUÉE (détection de vol, R2). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErreurApi"];
                };
            };
        };
    };
    config: {
        parameters: {
            query: {
                /** @description Zone dont on veut la configuration effective. */
                zone: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration effective résolue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigZone"];
                };
            };
            /** @description Non modifiée (If-None-Match == version). */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Paramètre zone absent ou UUID invalide. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Zone inconnue — erreur explicite, jamais une config vide. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate-limit dépassé. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service opérationnel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    moi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compte courant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompteMoi"];
                };
            };
            /** @description Session absente, invalide ou révoquée. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErreurApi"];
                };
            };
        };
    };
    mes_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Appareils actifs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionAppareil"][];
                };
            };
            /** @description Session absente, invalide ou révoquée. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErreurApi"];
                };
            };
        };
    };
    revoquer_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Appareil à déconnecter. */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session révoquée — événement `session.revoquee` émis. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session absente, invalide ou révoquée. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErreurApi"];
                };
            };
            /** @description Session inconnue ou n'appartenant pas au compte. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErreurApi"];
                };
            };
        };
    };
}
