name: mefali_design
description: Theme M3 marron et composants partages mefali
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mefali_core:
    path: ../mefali_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
