-- PostgreSQL does not support removing values from enums.
-- To revert, recreate the type without 'refused' (requires dropping/recreating dependent columns).
-- This is intentionally left as a no-op for safety.
